### ISSUE TITLE
mini SDK >16 ?

### ISSUE THREAD

**Issue by asker517** [satorufujiwara/material-scrolling#1]
nice work ~ :dango: 

but when i add compile 'jp.satorufujiwara:material-scrolling:1.0.0'  gradle task tell my mini SDK(14) smaller than this libray(16)

**Comment by satorufujiwara** [comment]
I fixed it, and released [1.0.1](https://github.com/satorufujiwara/material-scrolling/releases/tag/1.0.1).
Please try it, thanks.

**Comment by asker517** [comment]
OK! I just try to use [Android-PullToRefresh](https://github.com/chrisbanes/Android-PullToRefresh) or [android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) ..but this is seems not support the widget well ~ consider to support in the future?

**Comment by satorufujiwara** [comment]
Thank you for letting me know, but now I'm developing to use with [SwipeRefreshLayout](https://developer.android.com/intl/ja/reference/android/support/v4/widget/SwipeRefreshLayout.html) and it works well.
